Repository jamjam-book/be15-jamjam-bookjeok-front, pull requests merged in 2025-05, with the labels that each got.

#9 [REFACTOR] favicon 경로를 올바르게 설정
  index.html
Labels: ♻️ 리팩토링

#11 [FEAT] 책 이미지 위에 드롭다운 버튼 추가
  src/assets/css/header.css
  src/components/layout/Header.vue
Labels: 🤖 기능

#10 [REFACTOR] SearchBar icon 추가 및 경로 설정
  src/assets/icons/search.png
  src/components/common/SearchBar.vue
Labels: ♻️ 리팩토링

#13 [FEATURE] 장바구니 페이지 기능 구현
  index.html
  src/App.vue
  src/assets/images/cleancode.png
  src/assets/images/ddd.png
  src/assets/images/oop.png
  src/features/cart/router.js
  src/features/cart/views/CartItemView.vue
  src/features/cart/views/CartView.vue
  src/main.js
  src/router/index.js
Labels: 🤖 기능

#14 [FEATURE] 장바구니 아이콘 클릭 시 장바구니 페이지로 이동하는 기능 구현
  src/components/layout/Header.vue
Labels: 🤖 기능

#15 [FEAT] 비밀번호 재설정 페이지 만들기
  src/assets/css/formInput.css
  src/features/member/components/FormInput.vue
  src/features/member/router.js
  src/features/member/views/PasswordResetRequestView.vue
  src/features/member/views/PasswordResetView.vue
  src/router/index.js
Labels: 🤖 기능

#16 [REFACTOR] 장바구니 페이지에서 컴포넌트와 뷰를 명확하게 분리
  src/features/cart/components/CartItem.vue
  src/features/cart/components/CartSummary.vue
  src/features/cart/views/CartView.vue
Labels: ♻️ 리팩토링

#17 [FEATURE] 마이페이지 중첩 라우트 반영
  src/App.vue
  src/components/common/MyPageNav.vue
  src/features/member/router.js
  src/features/member/views/MyPageView.vue
Labels: 🤖 기능

#20 [FEATURE] 주문/결제 페이지 기능 구현
  package.json
  src/features/cart/cart.js
  src/features/order/components/MemberInfo.vue
  src/features/order/components/OrderItem.vue
  src/features/order/components/OrderSummary.vue
  src/features/order/components/TossPaymentWidget.vue
  src/features/order/router.js
  src/features/order/views/OrderAndPaymentView.vue
  src/features/order/views/OrderView.vue
  src/router/index.js
Labels: 🤖 기능

#21 [FEATURE] 장바구니와 주문/결제 페이지의 summary 위치가 동일하도록 코드 변경
  src/features/cart/components/CartItem.vue
  src/features/cart/components/CartSummary.vue
  src/features/cart/views/CartView.vue
Labels: 🤖 기능

#24 [FEATURE] 마이페이지 문의사항 기능 구현
  src/features/question/components/QuestionCategories.vue
  src/features/question/components/QuestionDetail.vue
  src/features/question/router.js
  src/features/question/views/QuestionEditView.vue
  src/features/question/views/QuestionListView.vue
  src/features/question/views/QuestionRegisterView.vue
  src/router/index.js
Labels: 🤖 기능

#25 [FIX] router/index.js 수정
  src/router/index.js
Labels: 🔨 수정

#22 [feature] Modal 확인만 있는 버젼, 페이징바 추가
  src/components/common/Modal2.vue
  src/components/common/PagingBar.vue
Labels: 🤖 기능

#26 [FIX] bootstrap의 css와 충돌 해결을 위해 클래스명 변경
  src/assets/css/header.css
  src/components/layout/Header.vue
Labels: 🐞 버그

#28 [FEATURE] 로그인 된 상태에서 비밀번호 변경 페이지 구현
  src/assets/css/formInput.css
  src/components/common/MyPageNav.vue
  src/features/member/components/FormInput.vue
  src/features/member/router.js
  src/features/member/views/PasswordModifyView.vue
Labels: 🤖 기능

#29 [FEATURE] 관심 작가 페이지 구현
  src/components/common/MyPageNav.vue
  src/features/member/components/InterestAuthorItem.vue
  src/features/member/components/InterestAuthorList.vue
  src/features/member/components/InterestTab.vue
  src/features/member/router.js
  src/features/member/views/InterestAuthorView.vue
Labels: 🤖 기능

#30 [FIX] PagingBar 버튼 색상 수정 및 Modal 창 속성 추가
  src/components/common/Modal.vue
  src/components/common/Modal2.vue
  src/components/common/PagingBar.vue
Labels: 🔨 수정

#32 [FEATURE] 주문/결제 완료 페이지 구현
  src/features/order/components/MemberAddressInfo.vue
  src/features/order/components/PaymentInfo.vue
  src/features/order/components/TossPaymentWidget.vue
  src/features/order/router.js
  src/features/order/views/OrderCompletionVIew.vue
  src/features/order/views/OrderView.vue
Labels: 🤖 기능

#33 [FEATURE] 관심 도서 페이지 구현
  src/assets/images/book1.jpg
  src/assets/images/book2.jpg
  src/features/member/components/InterestBookItem.vue
  src/features/member/components/InterestBookList.vue
  src/features/member/views/InterestBookView.vue
Labels: 🤖 기능

#36 [FEATURE] 문의사항 페이지 구현
  package.json
  public/images/main_482791348279137620.20240609071045.jpg
  src/features/member/router.js
  src/features/question/components/QuestionCategories.vue
  src/features/question/components/QuestionDetail.vue
  src/features/question/components/QuestionForm.vue
  src/features/question/router.js
  src/features/question/views/QuestionEditView.vue
  src/features/question/views/QuestionListView.vue
  src/features/question/views/QuestionRegisterView.vue
  src/router/index.js
Labels: ⚙ 세팅, 🤖 기능

#37 [REFACTOR] app container css 변경
  src/App.vue
Labels: ♻️ 리팩토링

#39 [FEATURE] 주문 내역 페이지 구현
  src/components/common/MyPageNav.vue
  src/features/member/router.js
  src/features/order/components/OrderCard.vue
  src/features/order/router.js
  src/features/order/views/MemberOrdersView.vue
Labels: 🤖 기능

#40 [FEATURE] 회원의 팔로잉 목록 페이지 만들기
  src/components/common/MyPageNav.vue
  src/features/member/components/FollowingItem.vue
  src/features/member/components/FollowingList.vue
  src/features/member/router.js
  src/features/member/views/FollowingView.vue
Labels: 🤖 기능

#43 [FEATURE] 주문 상세 내역 페이지 구현
  src/features/order/components/OrderDetailCard.vue
  src/features/order/router.js
  src/features/order/views/OrderCompletionVIew.vue
  src/features/order/views/OrderDetailView.vue
Labels: 🤖 기능

#46 [REFACTOR] 주문 상세 페이지 UI 개선, 구역 하단 구분선 및 텍스트 색상 적용
  src/features/order/components/MemberAddressInfo.vue
  src/features/order/components/OrderCard.vue
  src/features/order/components/OrderItem.vue
  src/features/order/components/PaymentInfo.vue
  src/features/order/components/TossPaymentWidget.vue
  src/features/order/views/OrderCompletionVIew.vue
  src/features/order/views/OrderView.vue
Labels: ♻️ 리팩토링

#49 [REFACTOR] 마이페이지 주문 내역 경로 변경
  src/components/common/MyPageNav.vue
  src/features/order/router.js
Labels: ♻️ 리팩토링

#50 [FEATURE] 팔로잉 하는 사람의 게시글 상세 페이지 구현
  src/assets/images/post01.jpg
  src/features/member/components/FollowingItem.vue
  src/features/post/components/PostItem.vue
  src/features/post/components/PostList.vue
  src/features/post/router.js
  src/features/post/views/MemberPostView.vue
  src/router/index.js
Labels: 🤖 기능

#52 [FEATURE] 관심 게시글 페이지 구현
  src/features/member/views/InterestPostView.vue
Labels: 🤖 기능

#53 [REFACTOR] 관심 탭에 라우터 설정 및 관심 작가, 관심 도서, 관심 게시글 중첩 라우터 형태로 변경
  src/components/common/MyPageNav.vue
  src/features/member/components/InterestTab.vue
  src/features/member/router.js
  src/features/member/views/InterestAuthorView.vue
  src/features/member/views/InterestBookView.vue
  src/features/member/views/InterestView.vue
Labels: ♻️ 리팩토링

#54 [FEATURE] 장바구니 수량 입력 개선 및 주문 정보 연동 구현
  src/features/cart/components/CartItem.vue
  src/features/cart/components/CartSummary.vue
  src/features/cart/views/CartView.vue
Labels: 🤖 기능

#56 [FEATURE] 관리자 도서 입고/수량 변경 페이지 구현
  src/features/admin/components/AdminBookInfoRow.vue
  src/features/admin/router.js
  src/features/admin/views/AdminBookDetailView.vue
  src/features/admin/views/AdminBookStoreView.vue
  src/router/index.js
Labels: 🤖 기능

#57 [FEATURE] 결제 및 주문 정보 API 연동 및 새로고침 대응 로직 추가
  src/features/order/components/MemberAddressInfo.vue
  src/features/order/components/OrderItem.vue
  src/features/order/components/TossPaymentWidget.vue
  src/features/order/views/OrderCompletionVIew.vue
  src/features/order/views/OrderCompletionView.vue
Labels: 🤖 기능

#58 [FEATURE] 구매 금액의 1%를 포인트로 적립해주는 기능 추가
  src/features/order/components/PaymentInfo.vue
Labels: 🤖 기능

#59 [FEATURE] sessionStorage를 활용해 주문/결제 페이지 새로고침 시 주문 정보 유지
  src/features/cart/cart.js
  src/features/cart/components/CartSummary.vue
  src/features/cart/views/CartView.vue
  src/features/order/components/TossPaymentWidget.vue
  src/features/order/views/OrderView.vue
Labels: 🤖 기능

#60 [FEATURE] Modal 메세지 가운데 정렬 및 단어 단위로 줄바꿈, LoginPage 기능 구현
  src/components/common/Modal.vue
  src/components/common/Modal2.vue
  src/components/layout/Header.vue
  src/features/main/router.js
  src/features/member/router.js
  src/features/member/views/LoginPage.vue
  src/router/index.js
Labels: 🤖 기능

#61 [FIX] totalPages를 백엔드에 있는 이름과 동일하게 수정
  src/components/common/PagingBar.vue
Labels: 🐞 버그, 🔨 수정

#63 [FEATURE] 관리자 도서 페이지 구현 및 API 연동
  src/features/admin/bookapi.js
  src/features/admin/router.js
  src/features/admin/views/AdminBookDetailView.vue
  src/features/admin/views/AdminBookStocksView.vue
  src/features/admin/views/AdminBookStoreView.vue
  src/features/admin/views/AdminView.vue
Labels: 🤖 기능

#65 [FIX] 도서나 게시글 버튼 클릭 시 페이지 이동과 함께 메뉴가 닫히도록 수정
  src/components/layout/Header.vue
Labels: 🔨 수정

#67 [FEATURE] 관리자 페이지 구현 및 api 연결 완료
  src/features/admin/components/AdminMemberList.vue
  src/features/admin/components/MemberItem.vue
  src/features/admin/components/MemberSearchBar.vue
  src/features/admin/memberApi.js
  src/features/admin/router.js
  src/features/admin/views/AdminMemberDetailView.vue
  src/features/admin/views/AdminMemberView.vue
Labels: ♻️ 리팩토링, 🤖 기능

#68 [FEATURE] 주문 상세 페이지에서 백엔드 API를 통해 실제 주문 데이터 조회 기능 구현
  src/features/order/components/MemberAddressInfo.vue
  src/features/order/router.js
  src/features/order/views/MemberOrdersView.vue
  src/features/order/views/OrderDetailView.vue
Labels: 🤖 기능

#69 [FIX] 결제 완료 페이지 응답 데이터 구조 변경에 따라 코드 수정 및 새로고침 시 정보 초기화 문제 해결
  src/features/order/views/OrderCompletionView.vue
Labels: ♻️ 리팩토링, 🐞 버그, 🔨 수정

#70 [FIX] 주문 내역에서 도서명이 출력되지 않던 문제 해결
  src/features/order/components/OrderCard.vue
Labels: 🐞 버그

#72 [STYLE] 주문 정보 레이아웃 통일 및 수량과 금액 위치 조정
  src/features/order/components/OrderCard.vue
  src/features/order/components/OrderDetailCard.vue
  src/features/order/components/OrderItem.vue
Labels: ♻️ 리팩토링

#74 [FEATURE] 비밀번호 재설정 api 연결하기
  src/features/member/passwordResetApi.js
  src/features/member/views/LoginPage.vue
  src/features/member/views/PasswordResetRequestView.vue
  src/features/member/views/PasswordResetView.vue
Labels: 🤖 기능

#75 [REFACTOR] import된 api 이름 변경
  src/features/member/views/PasswordResetRequestView.vue
  src/features/member/views/PasswordResetView.vue
Labels: ♻️ 리팩토링

#76 [REMOVE] 사용하지 않는 컴포넌트 삭제
  src/features/order/views/OrderAndPaymentView.vue
Labels: ♻️ 리팩토링

#77 [STYLE] 페이징바 margin 크기 조절
  src/components/common/PagingBar.vue
Labels: ♻️ 리팩토링

#80 [FEATURE] 관심 작가 조회, 추가, 삭제 api 연결하기
  src/features/member/components/InterestAuthorItem.vue
  src/features/member/interestApi.js
  src/features/member/views/InterestAuthorView.vue
Labels: 🤖 기능

#78 [STYLE] 주문 내역 페이지에서 날짜와 주문ID 간격 조절
  src/features/order/components/OrderCard.vue
Labels: ♻️ 리팩토링

#81 [FEATURE] 회원가입 페이지 구현
  src/components/common/Modal.vue
  src/components/common/Modal2.vue
  src/features/main/router.js
  src/features/member/router.js
  src/features/member/views/SignUp.vue
Labels: 🤖 기능

#83 [FEATURE] 팔로잉 api 연결하기
  src/features/member/components/FollowingItem.vue
  src/features/member/components/FollowingList.vue
  src/features/member/components/FormInput.vue
  src/features/member/interestApi.js
  src/features/member/views/FollowingView.vue
Labels: 🤖 기능

#84 [FEATURE] 메인 페이지 금주 인기 도서 컴포넌트 구현하기
  src/features/main/components/BookTopTen.vue
  src/features/main/router.js
  src/features/main/views/MainView.vue
Labels: 🤖 기능

#85 [FIX] 장바구니 API 응답 데이터 변환 및 엔드포인트 변경에 따라 컴포넌트 수정
  src/features/cart/views/CartView.vue
Labels: ♻️ 리팩토링, 🐞 버그

#86 [FEATURE] 관심 도서 api 연결하기
  src/features/member/components/InterestBookItem.vue
  src/features/member/interestApi.js
  src/features/member/views/InterestBookView.vue
  src/features/member/views/InterestView.vue
Labels: ♻️ 리팩토링, 🔨 수정, 🤖 기능

#87 [REFACTOR] 도서 관리자 api 연동 port 번호 변경
  src/features/admin/bookapi.js
  src/features/admin/views/AdminBookDetailView.vue
Labels: 🤖 기능

#88 [REFACTOR] 비밀번호 수정에서 유효성 검사 추가 및 스타일 수정
  src/features/member/views/PasswordModifyView.vue
Labels: ♻️ 리팩토링, 🔨 수정

#89 [FEATURE] 프로필 관리 페이지 구현
  src/components/common/Modal2.vue
  src/components/common/MyPageNav.vue
  src/components/layout/Header.vue
  src/features/main/router.js
  src/features/member/router.js
  src/features/member/views/ProfileView.vue
Labels: 🤖 기능

#90 [FEATURE] 메인 페이지에 인기 게시글 넣기
  src/features/main/components/PostTopTen.vue
  src/features/main/views/MainView.vue
Labels: 🤖 기능

#93 [FEATURE] 사용자 도서 목록 및 상세 페이지 구현하기 및 api 연동
  package.json
  src/App.vue
  src/components/common/LoadingSpinner.vue
  src/features/book/api.js
  src/features/book/components/AuthorOtherBooks.vue
  src/features/book/components/BookCard.vue
  src/features/book/components/BookDescription.vue
  src/features/book/components/BookInfoHeader.vue
  src/features/book/components/BookListFilter.vue
  src/features/book/components/BookReviews.vue
  src/features/book/components/BookTabs.vue
  src/features/book/views/BookDetailView.vue
  src/features/book/views/BookListView.vue
Labels: ♻️ 리팩토링, ⚙ 세팅, 🤖 기능

#91 [FEATURE] 장바구니에 있는 도서 정보 개수 만큼 장바구니 아이콘 우측 상단에 개수를 표시하는 기능 구현
  src/assets/css/header.css
  src/components/layout/Header.vue
  src/features/order/views/OrderCompletionView.vue
Labels: 🤖 기능

#94 [FEATURE] 상황에 알맞는 모달창 추가
  src/features/member/views/SignUp.vue
Labels: 🤖 기능

#96 [FIX] 장바구니 이미지 경로 처리 로직 수정
  src/features/cart/components/CartItem.vue
  src/features/order/components/OrderCard.vue
  src/features/order/components/OrderDetailCard.vue
  src/features/order/components/OrderItem.vue
Labels: ♻️ 리팩토링, 🐞 버그

#95 [FEATURE]: LoginPage, SignUp pinia 연동
  src/features/member/views/LoginPage.vue
  src/features/member/views/SignUp.vue
  src/lib/axios.js
  src/lib/user.js
  src/stores/auth.js
Labels: 🤖 기능

#98 [FEATURE] 메인 페이지 컴포넌트 구현 및 api 연동
  src/components/layout/Header.vue
  src/features/book/views/BookListView.vue
  src/features/main/api.js
  src/features/main/components/BookTopTen.vue
  src/features/main/components/Categories.vue
  src/features/main/views/MainView.vue
Labels: ♻️ 리팩토링, 🤖 기능

#99 [FIX] 삭제된 헤더 토글 복구
  src/components/layout/Header.vue
Labels: 🐞 버그

#100 [FEAT] 도서를 장바구니에 등록하는 기능 구현
  src/features/book/components/BookInfoHeader.vue
Labels: 🤖 기능

#101 [FEAT] 도서 상세 페이지에서 주문하기 버튼 클릭 시 주문/결제 페이지로 이동하는 기능 구현
  src/features/book/components/BookInfoHeader.vue
Labels: 🤖 기능

#102 [FEAT] 장바구니 페이지 최초 진입 시 자동 새로고침 기능 추가
  src/features/cart/views/CartView.vue
Labels: 🤖 기능

#103 [FIX] keyword 검색 및 전체 도서 조회 시 api 미호출 버그 수정
  src/features/book/components/BookListFilter.vue
  src/features/book/views/BookListView.vue
Labels: 🐞 버그, 🔨 수정

#107 [FEATURE] 로그인 성공 시 헤더부분 변경 기능, 새로고침해도 로그인 상태 유지, 로그인 상태에 따른 헤더 구성요소들 위치 통일
  package-lock.json
  package.json
  src/components/layout/Header.vue
  src/main.js
  src/stores/auth.js
Labels: 🤖 기능

#110 [FEAT] 헤더와, 주문 성공 페이지 경로 설정 올바르게 수정
  src/components/layout/Header.vue
  src/features/order/views/OrderCompletionView.vue
Labels: 🔨 수정, 🤖 기능

#114 [FIX] 도서 리뷰 등록 시 변경 데이터 반영
  src/features/book/components/BookReviews.vue
Labels: 🐞 버그, 🔨 수정
